server:
  port: 9091

spring:
  application:
    name: course
  datasource:
    url: jdbc:postgresql://localhost:5432/db_course
    username: 'postgres'
    password: 'password'
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update
    database: postgresql

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/