server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/students/**
        - id: courses
          uri: http://localhost:9091
          predicates:
            - Path=/api/v1/courses/**
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
